### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/jsdoc-typescript-plugin#33]
We have documented it in source, but not as an accessible markdown file

**Comment by jumpinjackie** [comment]
Documentation Checklist:
- [ ] Configuration section reference (CONFIGURATION.md)
- [ ] How `@inheritDoc` is handled
- [ ] How nullability/optionality is determined in function arguments
- [ ] Automatic interface generation (when #25 is implemented)
- [ ] String enums (when #41 is implemented)
- [ ] How nested (ie. Tildefied) types are handled (when #24 and #48 is implemented)
- [ ] AMD module notes
- [ ] Module structure (ie. The plugin doesn't know how, so explain how to output expected module structure)
- [ ] Notes about default argument values for functions (ie. They aren't supported in TypeScript)
- [ ] How `undefined` as part of a union of types is translated
  - [ ] If parameter type, makes parameter optional
  - [ ] If return type, has no effect
- [ ] Known Limitations
  - [ ] Enums must have explicit literal values (and not an assignment from another source)
- [ ] Closure: TS interface generation from `@record` annotation
